# This is a sample deployment file that uses Kata Containers's peer pods as the
# runtime class called kata-remote for the pod. This example is used to showcase
# policy enforcement.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      runtimeClassName: kata-remote
      containers:
        - name: nginx
          image: "quay.io/surajd/nginx:1.27.2-alpine"
          ports:
            - containerPort: 80
          imagePullPolicy: Always
