name: Build & Push

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # Download code.
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor}}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate Tag
      id: tag
      run: |
        # Generate a tag based on the commit hash and current timestamp.
        # The format is <branch>-<commit hash>-<timestamp>.
        echo "image_tag=$(git rev-parse --abbrev-ref HEAD)-$(git rev-parse --short HEAD)-$(date '+%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

    - name: Extract metadata labels for base image
      id: meta-base
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/surajssd/kubecon-na24-workshop-base
        tags: |
          type=raw,value=${{ steps.tag.outputs.image_tag }}
          type=raw,value=latest

    - name: Base image
      uses: docker/build-push-action@v6
      with:
        file: Dockerfile
        push: true
        tags: ${{ steps.meta-base.outputs.tags }}
        labels: ${{ steps.meta-base.outputs.labels }}

    - name: Extract metadata labels for demo 2 image
      id: meta-demo2
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/surajssd/kubecon-na24-workshop-demo2
        tags: |
          type=raw,value=${{ steps.tag.outputs.image_tag }}
          type=raw,value=latest

    - name: Demo 2 application image
      uses: docker/build-push-action@v6
      with:
        file: demos/demo2/app/Dockerfile
        context: demos/demo2/app
        push: true
        tags: ${{ steps.meta-demo2.outputs.tags }}
        labels: ${{ steps.meta-demo2.outputs.labels }}
